services:
  backend:
    build: ./backend
    ports:
      - "5000:5000" # Port máy host : port container (phải khớp EXPOSE 5000 trong Dockerfile)
    env_file:
      - ./backend/.env # Load biến môi trường cho backend

  frontend:
    build: ./frontend
    ports:
      - "3000:80" # Map port 3000 (host) -> 80 (container, thường dùng Nginx)